### ISSUE TITLE
Facebook and Viber icon not reflecting on version 15 com.android.launcher3

### ISSUE THREAD

**Issue by keyjeyelpi** [RichardLuo0/global-icon-pack-android#70]
**Describe the bug**
Facebook and Viber icons show the default icon instead of their Global Icon Pack counterpart.

**To Reproduce**
1. Add com.android.launcher3 on lsposed.
2. Open facebook and viber
3. Facrbook and viber icons should be as selected on global icon pack

**Expected behavior**
show chosen icons for facebook and Viber on recents instead of their default

**Screenshots**
![Image](https://github.com/user-attachments/assets/55ef7315-af10-4000-adbc-1df5879fd136)
![Image](https://github.com/user-attachments/assets/81c81551-0cc5-402f-bd5f-5c88a5b94f19)

**Smartphone (please complete the following information):**
 - Device: Poco F6 Pro (Vermeer)
 - OS: BlackIron (Android 15)
 - Version: 5.7

**Additional context**

**Comment by RichardLuo0** [comment]
Hi did you try enabling "icon pack as fallback" in general settings?

**Comment by keyjeyelpi** [comment]
> Hi try enabling "icon pack as fallback" in general settings

Hi, I tried enabling it, but it's still the same. Here's a screenshot showing that it's enabled along with Facebook on the recents. 

![Screenshot_20250429-061348_Blackiron Home.png](https://github.com/user-attachments/assets/73e2de13-8647-438d-a77c-b0e5e2cb0941)

**Comment by RichardLuo0** [comment]
This is because Facebook uses `setTaskDescription` to set its task icon dynamically. It should be used in scenarios such as a browser (use website icon as task icon). But for some reason Facebook uses it to change its main icon.
This is a tricky one to do, because replacing this icon may affect Chrome tabs (which is used by many apps).

**Comment by RichardLuo0** [comment]
Should be fixed in 0.3.9. Enable `Force load activity icon for task` in pixel settings.

**Comment by keyjeyelpi** [comment]
How about for Viber? After Checking, Viber's icon is still the same as well. 

![Screenshot_20250430-061222_Blackiron Home.png](https://github.com/user-attachments/assets/d7b39bc0-d3dd-42b8-9b6e-532cf241d9fd)

**Comment by keyjeyelpi** [comment]
Installed the latest GIP, and it's still the same. 

![Screenshot_20250430-094445_Blackiron Home.png](https://github.com/user-attachments/assets/e2e53004-5a8f-45c6-825b-8edd76ee6e43)

**Comment by RichardLuo0** [comment]
Did you check the force load activity icon for task? And btw, what is the launcher you are using? Did you input a different launcher package name?

**Comment by keyjeyelpi** [comment]
> Did you check the force load activity icon for task? 
- Yes, I have enabled it as well as restarted the device. 

> And btw, what is the launcher you are using?
- it's BlackIron home (default home of the BlackIron ROM). Package name is com.android.launcher3, same as every other ROM.

> Did you input a different launcher package name?
- launcher name is still the default value, which is com.google.android.apps.nexuslauncher

**Comment by RichardLuo0** [comment]
You must input `com.android.launcher3` into the launcher package name.

**Comment by RichardLuo0** [comment]
> Package name is com.android.launcher3, same as every other ROM.

It is not the same as "every other ROM". The default in GIP is `com.google.android.apps.nexuslauncher`.

**Comment by keyjeyelpi** [comment]
It's working now. Thank you for clarifying
